name: OpenVidu Call CI/CD
on:
  schedule: # default branch (master)
    - cron: '* 0 * * *'
  push:
    branches:
      - master
      - 'feature/**'
  pull_request:
    branches:
      - master
  release:
    types: [created]

jobs:

  unit_test:
    name: Unit test
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Cache multiple paths
      uses: actions/cache@v2
      with:
        path: |
          ~/cache
          !~/cache/exclude
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Remove package-lock
      run: rm openvidu-call-front/package-lock.json
    - name: Install dependencies
      run: npm install --prefix openvidu-call-front
    - name: Run unit tests
      run: npm run test --prefix openvidu-call-front


  e2e_test:
    name: E2E test
    runs-on: ubuntu-latest
    if: github.ref != 'feature/**' && github.event_name != 'pull_request'
    steps:
    - uses: actions/checkout@v2
    - name: Install ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome --version | cut -f 3 -d ' ' | cut -d '.' -f 1) \
        && CHROMEDRIVER_RELEASE=$(curl --location --fail --retry 3 http://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}) \
        && curl --silent --show-error --location --fail --retry 3 --output /tmp/chromedriver_linux64.zip "http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_RELEASE/chromedriver_linux64.zip" \
        && cd /tmp \
        && unzip chromedriver_linux64.zip \
        && rm -rf chromedriver_linux64.zip \
        && sudo mv chromedriver /usr/local/bin/chromedriver \
        && sudo chmod +x /usr/local/bin/chromedriver \
        && chromedriver --version
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Cache multiple paths
      uses: actions/cache@v2
      with:
        path: |
          ~/cache
          !~/cache/exclude
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Start OpenVidu
      run: docker run -p 4443:4443 --rm -d -e OPENVIDU_SECRET=MY_SECRET openvidu/openvidu-server-kms:2.14.0
    - name: Install dependencies
      run: |
        npm install --prefix openvidu-call-front
        npm i --prefix openvidu-call-back
    - name: Start OpenVidu Call back
      run: npm start --prefix openvidu-call-back &
    - name: Running E2E test
      run: npm run e2e --prefix openvidu-call-front

  qa_sonar:
    name: QA and Security with Sonar
    runs-on: ubuntu-latest
    if: github.ref != 'feature/**' && github.event_name != 'pull_request'
    steps:
    - name: QA Sonar
      run: echo "TODO Sonar"

  nightly:
    name: Deploy nightly
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    needs: [unit_test, e2e_test, qa_sonar]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Getting timestamp
      id : time
      uses: nanzm/get-time-action@v1.0
      with:
        timeZone: 8
        format: 'YYYY-MM-DD-HH-mm-ss'
    - name: Build OpenVidu Call front
      run: |
        npm install --prefix openvidu-call-front
        npm run build-prod --prefix openvidu-call-front
    - name: Build OpenVidu Call back
      run: |
        npm i --prefix openvidu-call-back
        npm run build --prefix openvidu-call-back
        mkdir release && cp openvidu-call-back/dist/ -r release
    - uses: actions/upload-artifact@v2
      with:
        name: openvidu-call-${{ steps.time.outputs.time }}
        path: release

  release:
    name: Deploy release
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    needs: [unit_test, e2e_test, qa_sonar]
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Registry
      env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u "$DOCKER_USERNAME" --password-stdin <<< "$DOCKER_PASSWORD"
    - name: Building and publishing docker image in Docker Hub
      run: |
        chmod +x docker/run.sh
         ./docker/run.sh ${{ github.ref }}